Nexters/payout-client

- package.json
- pnpm-lock.yaml
- src/app/(landing)/_components/faq.tsx
- src/app/(landing)/_components/footer.tsx
- src/app/(landing)/_components/header.tsx
- src/app/(landing)/layout.tsx
- src/app/(landing)/page.tsx
- src/components/Button/Button.tsx
- src/components/icons/chevron-down.tsx
- src/components/ui/accordion.tsx
- tailwind.config.ts
> feat(landing): 푸터를 포함한 랜딩페이지 작업 

- src/app/(main)/report/dividend/_components/dividend-row.tsx
- src/app/(main)/report/dividend/monthly/_components/dividend-accordion.tsx
- src/app/(main)/report/dividend/monthly/_components/header.tsx
- src/app/(main)/report/dividend/monthly/page.tsx
- src/app/(main)/report/dividend/yearly/_components/dividend-list.tsx
- src/app/(main)/report/dividend/yearly/_components/header.tsx
- src/app/(main)/report/dividend/yearly/page.tsx
- src/app/(main)/report/page.tsx
- src/app/(main)/ticker/page.tsx
- src/app/layout.tsx
- src/components/common/navigation-bar/navigation-bar.tsx
- src/components/ui/accordion.tsx
close: #12 #13 
- UI 작업이 대부분이었던 페이지들이라 딱히 없습니다!
> feat(report): Implement Monthly/Yearly Dividend Ranking Pages

- src/app/(main)/report/sector-detail/_components/dividend-list.tsx
- src/app/(main)/report/sector-detail/_components/header.tsx
- src/app/(main)/report/sector-detail/_components/sector-insights-item.tsx
- src/app/(main)/report/sector-detail/_components/sector-insights.tsx
- src/app/(main)/report/sector-detail/page.tsx
- src/app/globals.css
- src/utils/data.ts
close: #16 
- 의존성 목록
- UI 작업입니다! 
>  feat: implement sector detail page

- src/app/(main)/report/sector-detail/_components/header.tsx
- src/app/(main)/report/sector-detail/_components/sector-insights-item.tsx
- src/app/(main)/report/sector-detail/_components/sector-insights.tsx
- src/components/common/navigation-bar/navigation-bar.tsx
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> style: fix the design qa on sector detail page

- src/app/(main)/report/sector-detail/_components/header.tsx
- src/app/(main)/report/sector-detail/_components/sector-insights-item.tsx
- src/app/(main)/report/sector-detail/_components/sector-insights.tsx
- src/app/(main)/ticker/_components/intro.tsx
- src/app/(main)/ticker/_components/ticker-content.tsx
- src/app/(main)/ticker/_components/ticker-drawer.tsx
- src/app/(main)/ticker/_components/ticker-footer.tsx
- src/components/common/navigation-bar/navigation-bar.tsx
- src/components/ui/input.tsx
close: X
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> style: fix the design qa on ticker

- src/app/(landing)/_components/faq.tsx
- src/app/(landing)/_components/monthly-dividend.tsx
- src/app/(landing)/page.tsx
- src/components/common/button/button.tsx
close: X
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> style: apply qa review on landing page

- src/app/(main)/report/sector-detail/_components/header.tsx
- src/app/(main)/report/sector-detail/_components/sector-insights-item.tsx
- src/app/(main)/report/sector-detail/_components/sector-insights.tsx
- src/app/(main)/report/sector-detail/page.tsx
- src/app/(main)/stock/[id]/_components/dividend-info.tsx
- src/app/(main)/stock/[id]/_components/header.tsx
- src/app/(main)/stock/[id]/_components/investment-tip.tsx
- src/app/(main)/stock/[id]/_components/stock-drawer.tsx
- src/app/(main)/stock/[id]/_data/index.ts
- src/app/(main)/stock/[id]/page.tsx
- src/app/(main)/ticker/_components/intro.tsx
- src/app/(main)/ticker/_components/ticker-list.tsx
- src/components/common/toast/toast.tsx
- src/components/ui/drawer.tsx
- src/components/ui/input.tsx
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> style: apply qa review on stock detail

- src/app/(main)/stock/[id]/_components/investment-tip.tsx
- src/app/(main)/stock/[id]/_components/stock-drawer.tsx
- src/app/(main)/ticker/_components/ticker-drawer.tsx
- src/components/ui/drawer.tsx
- src/components/ui/input.tsx
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> style: apply design qa

- src/app/(main)/stock/[id]/page.tsx
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> style: apply body style on drawer

- src/app/(main)/stock/[id]/_components/stock-drawer.tsx
- src/app/(main)/ticker/_components/intro.tsx
- src/app/(main)/ticker/_components/ticker-content.tsx
- src/app/(main)/ticker/_components/ticker-drawer.tsx
- src/app/(main)/ticker/_components/ticker-footer.tsx
- src/app/(main)/ticker/_components/ticker-list.tsx
- src/components/common/dialog/dialog.tsx
- src/components/common/toast/toast.tsx
- src/components/ui/dialog.tsx
- src/components/ui/drawer.tsx
- src/components/ui/input.tsx
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> style: apply design qa on ticker-input page

- src/app/(main)/ticker/_components/ticker-content.tsx
- src/components/common/toast/toast.tsx
- src/components/ui/input.tsx
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> style: apply design qa 24.02.27

- src/app/(main)/report/_components/monthly-dividend.tsx
- src/app/(main)/report/page.tsx
close: #43 
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> feat: backend Integration on report page for monthly dividend bar charts

- src/app/(main)/report/sector-detail/_components/sector-insights-item.tsx
- src/app/(main)/report/sector-list/page.tsx
- src/app/(main)/stock/[id]/_components/dividend-info.tsx
- src/app/(main)/stock/[id]/_components/investment-tip.tsx
- src/app/(main)/stock/[id]/page.tsx
- src/state/queries/get-stock-by-ticker.ts.ts
close: #42 
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> feat: implement api on stock detail page

- src/api/generated/endpoint.schemas.ts
- src/api/generated/endpoint.ts
- src/app/(main)/report/sector-detail/_components/sector-insights-item.tsx
- src/app/(main)/report/sector-detail/_components/sector-insights.tsx
- src/state/queries/use-biggest-dividend-yield-stocks.ts
- src/state/queries/use-coming-dividend-stocks.ts.ts
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> feat: add lastModifiedAt data

- src/app/(main)/report/_components/monthly-dividend.tsx
- src/app/(main)/report/dividend/monthly/_components/dividend-accordion.tsx
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> fix: design qa

- package.json
- pnpm-lock.yaml
- src/app/ga-provider.tsx
- src/app/global-provider.tsx
> feat: Hotjar 설치

- src/app/(landing)/_components/floating-footer.tsx
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> fix: fix btn click event

- src/api/generated/endpoint.schemas.ts
- src/api/generated/endpoint.ts
- src/app/(input)/ticker/_components/ticker-footer.tsx
- src/app/(main)/report/[id]/page.tsx
- src/state/mutations/use-portfolio-mutation.tsx
- src/state/queries/use-monthly-dividend-mutation.ts
- src/state/queries/use-stocks-sector-ratio-mutation.ts
- src/state/queries/use-yearly-dividend-mutation.ts
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> feat: update mutation method to new api

- src/app/(main)/report/[id]/sector-list/page.tsx
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> fix: fix build error

- src/app/(main)/report/[id]/sector-detail/_components/sector-insights-item.tsx
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> fix: fix placeholder image
